#ifndef _TEXTUREMAP_h
#define _TEXTUREMAP_h
#include <PCH/pch.h>
#include "stb_image.h"


struct Texture {
	GLuint textureID; //This is the gl id
	long long textureHash; //The texture has is the hash generated by the texturemap
	int refCount; //How many objects are currently using this texture
};

class TextureMap {
public:	
	static TextureMap* getInstance();

	void destroy();
	//Insert a new texture into the map of textures
	GLuint insert(const std::string& textureName, const std::string& textureFile);
	
	const GLuint& getTextureID(const std::string& name);
	//Remove a specific texture
	void removeTexture(const long long& hash);
	//Removes all textures
	void removeAll();

	//Dumps all of the texture data
	void dump();

	const int& totalNumberOfDuplicates() const;
private:
	TextureMap();
	~TextureMap();

	long long hash(const std::string& title);
	static TextureMap* m_textureMap;
	std::map<long long, Texture> m_textures;
	
	long long m_sizeofSavedData; //Represents how many bites have been saved from texture mapping
	int m_totalDuplicates;		 //Represents the total amount of duplicated textures that has been loaded

};


#endif